### ISSUE TITLE
provison whole directory output to S3 

### ISSUE THREAD

**Issue by byb121** [dockstore/s3cmd-plugin#9]
it seems that s3cmd-plugin can not handle this: 

```
outputs:
  result_data:
    type: Directory
    outputBinding:
      glob: $(inputs.exp_name)
```

```
  "result_data":{
    "path":"s3cmd://tmp/dstore_test/out/",
    "class":"Directory"
  }
```
Dockstore exits normally, but results folder is not provisioned to S3.
